### ISSUE TITLE
5.1 dont store the settings

### ISSUE THREAD

**Issue by TedBax** [kinitawowi/linkvisitor-firefox#2]
(sorry, bad english)
Win7 x32 german, LinkVisitor 5.1, Firefox 56 x32 german.

At every new start of Firefox I must set the settings again and again.
My Firefox-Profile is on a network-partition. 
is this a problem?
Where did LV store it settings?

LV v4.x was ok.

**Comment by kinitawowi** [comment]
Mozilla have changed the storage mechanism for new plugins, making life a bit trickier.

The plugin helper I'm using stores the preferences in the background windows local storage,  which it turns out is a bad idea.  I've updated the plugin to use the proper storage API  which will browser.storage.local by default.  (which is stored in the users profile)

If browser.storage.sync is enabled,  that will be used in preference to local storage.
To enable syncronised storage set webextensions.storage.sync.enabled to true in about:config

**Comment by kinitawowi** [comment]
The preferences do not appear to be saved as expected,  storage.sqlite not updating

**Comment by kinitawowi** [comment]
I've resolved the issue with preference saving  (hopefully).

For reference,  the preferences are stored in:
    [profile-directory]/browser-extension-data/{9C013B6E-46FC-11DD-B644-FC4D56D89593}/storage.js

**Comment by TedBax** [comment]
kinitawowi,

now it works for me!

I set the settings and restart firefox.
And now the settings from me are all there.
Problem is solved!

Thank you VERY MUCH for your great work.
